AWSTemplateFormatVersion: '2010-09-09'

Description: Provision Elastic IP address 

Resources:
  rEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:  
  oEip:
    Value: !Ref rEip
    Export:
      Name: !Sub ${AWS::StackName}::address

  oEipAllocationId:
    Value: !GetAtt rEip.AllocationId
    Export:
      Name: !Sub  ${AWS::StackName}::allocation-id